still got this : 
cat /etc/pgadmin4/config_local.py
# pgAdmin 4 configuration for external PostgreSQL
CONFIG_DATABASE_URI = "postgresql://pgadmin4:dEK4wM8d4\6sNi9p*Py5@host:12400/  pgadmin_dev
"

DATA_DIR = '/pgadmin/data'
LOG_FILE = '/var/log/pgadmin4/pgadmin4.log'

instead of this : 
cat /etc/pgadmin4/config_local.py
# pgAdmin 4 configuration for external PostgreSQL
CONFIG_DATABASE_URI = "postgresql://pgadmin4:dEK4wM8d4\6sNi9p*Py5@hostn:12400/pgadmin_dev"

DATA_DIR = '/pgadmin/data'
LOG_FILE = '/var/log/pgadmin4/pgadmin4.log'

here's the ansible tasks: 
- name: Set pgAdmin4 database name based on ENVI
  set_fact:
    pgadmin_db_name: >-
      {% if ENVI == 'oat' %}
        {{ vault_secret_response.json.data.data.pgadmin_db_name_oat | trim | replace('\n', '') }}
      {% elif ENVI == 'prd' %}
        {{ vault_secret_response.json.data.data.pgadmin_db_name_prd | trim | replace('\n', '') }}
      {% else %}
        "unknown_environment"
      {% endif %}

- name: Configure pgAdmin to use external PostgreSQL
  become: true
  template:
    src: config_local.py.j2
    dest: /etc/pgadmin4/config_local.py
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache HTTPD
