 cat /etc/pgadmin4/config_local.py
# pgAdmin 4 configuration for external PostgreSQL
CONFIG_DATABASE_URI = "postgresql://pgadmin4:dEK4wM8d4\\6sNi9p*Py5@host:12400/pgadmin_dev"
DATA_DIR = '/pgadmin/data'
LOG_FILE = '/var/log/pgadmin4/pgadmin4.log'
APP_DIR = '/usr/pgadmin4'[0][root@pgadmin4_oat_blue_1:/home/cloud-user]
$ ls /var/lib/pgadmin/
azurecredentialcache  pgadmin4.db  sessions  storage
[0][root@pgadmin4_oat_blue_1:/home/cloud-user]
$ cat /var/log/pgadmin4/pgadmin4.log
cat: /var/log/pgadmin4/pgadmin4.log: No such file or directory

