why this command "python3 /tmp/psycopg2-2.9.10/setup.py build"directly on server work and with ansible not working ..": FAILED! => {"changed": true, "cmd": ["python3", "/tmp/psycopg2-2.9.10/setup.py", "build"], "delta": "0:00:00.212062", "end": "2024-12-19 10:48:55.150795", "msg": "non-zero return code", "rc": 1, "start": "2024-12-19 10:48:54.938733", "stderr": "Traceback (most recent call last):\n  File \"/tmp/psycopg2-2.9.10/setup.py\", line 522, in <module>\n    for define in parser.get('build_ext', 'define').split(','):\n  File \"/usr/lib64/python3.9/configparser.py\", line 781, in get\n    d = self._unify_values(section, vars)\n  File \"/usr/lib64/python3.9/configparser.py\", line 1152, in _unify_values\n    raise NoSectionError(section) from None\nconfigparser.NoSectionError: No section: 'build_ext'", "stderr_lines": ["Traceback (most recent call last):", "  File \"/tmp/psycopg2-2.9.10/setup.py\", line 522, in <module>", "    for define in parser.get('build_ext', 'define').split(','):", "  File \"/usr/lib64/python3.9/configparser.py\", line 781, in get", "    d = self._unify_values(section, vars)", "  File \"/usr/lib64/python3.9/configparser.py\", line 1152, in _unify_values", "    raise NoSectionError(section) from None", "configparser.NoSectionError: No section: 'build_ext'"], "stdout": "", "stdout_lines": []}"
